services:
  postgres:
    image: postgres:17-alpine
    container_name: anzu-postgres
    restart: unless-stopped
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "postgres" -d "postgres"']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: anzu-redis
    restart: unless-stopped
    command: redis-server --requirepass ${DB_REDIS_PASSWORD:-example_redis_pw!} --port ${DB_REDIS_PORT:-6379}
    ports:
      - '${DB_REDIS_PORT:-6379}:${DB_REDIS_PORT:-6379}'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '${DB_REDIS_PORT:-6379}', '-a', '${DB_REDIS_PASSWORD:-example_redis_pw!}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    image: anzu-info
    container_name: anzu-info
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=redis

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: anzu-jenkins
    restart: unless-stopped
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  prisma-studio:
    image: node:22-alpine
    container_name: anzu-prisma-studio
    restart: unless-stopped
    working_dir: /usr/src/app
    ports:
      - '5555:5555'
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/usr/src/app
    command: >
      sh -c "npm install prisma && npx prisma generate && npx prisma studio --port 5555 --hostname 0.0.0.0"
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: anzu-npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./docker/npm/data:/data
      - ./docker/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
  jenkins_home:

